logging:
  level:
    org.springframework.dsl: trace
    org.eclipse.lsp4j: trace
spring:
  dsl:
    lsp:
      server:
        mode: WEBSOCKET
demo:
  wordcheckdsl:
    words:
    - "all"
    - "work"
    - "and"
    - "no"
    - "play"
    - "makes"
    - "jack"
    - "a"
    - "dull"
    - "boy"
