logging:
  file: simpledslprocessserver.log
  level:
    org.springframework.dsl: debug
spring:
  main:
    banner-mode: "off"
  dsl:
    lsp:
      server:
        mode: PROCESS
        force-jvm-exit-on-shutdown: true
