logging:
  file: simpledslprocessserver.log
  level:
    root: debug
    org.springframework.dsl: trace
    org.eclipse.lsp4j: trace
spring:
  main:
    banner-mode: "off"
  dsl:
    lsp:
      server:
        mode: PROCESS
        force-jvm-exit-on-shutdown: true
